# -*- coding: utf-8 -*-
"""Catalogo curado da BVC: repositorio -> (categoria, uso pratico, modelo de renda do doc 01).
Fonte das estrelas/licencas: dados/repos.csv e dados/extras.csv (verificados via API do GitHub)."""

CATALOGO = [
("Bases prontas de SaaS (boilerplates)", [
 ("wasp-lang/open-saas","Starter completo (React+Node): auth, billing, admin, blog, multi-tenant. O mais completo e gratuito.","6/8"),
 ("nextjs/saas-starter","Next.js + Postgres + Stripe + shadcn: o padrao minimalista para lancar em dias.","6"),
 ("vercel/nextjs-subscription-payments","Referencia oficial de assinaturas com Stripe + Supabase (ARQUIVADO em 2026 - use como estudo; base nova: nextjs/saas-starter).","6"),
 ("mickasmt/next-saas-stripe-starter","Next.js 14 + Auth.js + Prisma + Resend, com painel admin.","6"),
 ("ixartz/SaaS-Boilerplate","Next.js + Clerk + Drizzle: multi-tenancy, i18n, testes e landing.","6/8"),
 ("scosman/CMSaasStarter","SvelteKit + Supabase: leve, otimo para produto simples e rapido.","6"),
 ("nextify-limited/saasfly","Next.js + NextAuth + Prisma, com foco enterprise.","6"),
 ("async-labs/saas","Monorepo (Next+Express+Mongo): bom para estudar arquitetura de SaaS.","6"),
 ("alifarooq9/launchmvpfast","Componentes e blocos de UI para acelerar MVP.","6"),
 ("KolbySisk/next-supabase-stripe-starter","Base enxuta Next+Supabase+Stripe.","6"),
 ("d-ivashchuk/cascade","Boilerplate simples e extensivel.","6"),
 ("openstarterkit/nextjs-saas-starter-kit","Minimalista: Better Auth + Stripe + Prisma sem framework extra.","6"),
]),
("Backend, banco de dados, auth e storage", [
 ("supabase/supabase","Postgres + auth + storage + realtime + RLS. A base mais popular para micro-SaaS.","6/8"),
 ("appwrite/appwrite","Backend-as-a-service self-hosted (auth, DB, storage, functions).","6"),
 ("pocketbase/pocketbase","1 binario Go com SQLite, auth, realtime e admin. Imbatível para MVP solo.","6"),
 ("nhost/nhost","Postgres + GraphQL + auth, open source.","6"),
 ("hasura/graphql-engine","GraphQL instantaneo sobre Postgres.","6/7"),
 ("directus/directus","CMS/dados headless: vira painel de gestao do cliente em horas.","3/6"),
 ("payloadcms/payload","CMS em TypeScript, code-first, com admin excelente.","3/6"),
 ("strapi/strapi","CMS headless tradicional, ecossistema grande.","3/6"),
 ("better-auth/better-auth","Auth completa em TypeScript (OAuth, passkeys, organizacoes).","6"),
 ("supertokens/supertokens-core","Auth com sessao, roles e multi-tenancy.","6/8"),
 ("ory/kratos","Identidade e login self-hosted, nivel enterprise.","6/8"),
 ("unkeyed/unkey","API keys, rate limit e medicao de uso (ideal para modelo 7).","7"),
 ("pgvector/pgvector","Busca vetorial dentro do Postgres: RAG sem banco novo.","6/8"),
 ("meilisearch/meilisearch","Busca instantanea, otima UX de busca interna.","6"),
 ("typesense/typesense","Busca tolerante a erros, alternativa ao Algolia.","6"),
]),
("Pagamento, billing e financeiro", [
 ("juspay/hyperswitch","Orquestrador de pagamentos (multiplas adquirentes, roteamento, retry).","6/7"),
 ("getlago/lago","Billing por uso/assinatura open source (alternativa ao Chargebee).","6/7"),
 ("openmeterio/openmeter","Medicao de uso e faturamento por consumo (APIs de IA).","7"),
 ("invoiceninja/invoiceninja","Faturas, cobranca e portal do cliente.","3/6"),
 ("solidtime-io/solidtime","Controle de horas (base para cobrar por hora/projeto).","2/4"),
 ("kimai/kimai","Timesheet e relatorios de horas por cliente.","2/4"),
]),
("CRM, atendimento e comunicacao com cliente", [
 ("twentyhq/twenty","CRM moderno open source: pipeline, leads, atividades.","3/4"),
 ("chatwoot/chatwoot","Atendimento multicanal (WhatsApp, e-mail, chat). Substitui Zendesk/Intercom.","3/6"),
 ("zammad/zammad","Help desk completo com SLA e automacoes.","3/6"),
 ("freescout-help-desk/freescout","Help desk leve com shared inbox.","3/6"),
 ("knadh/listmonk","Newsletter e listas de e-mail de alta performance (self-host).","5/9/10"),
 ("novuhq/novu","Infra de notificacoes (e-mail, SMS, push, in-app) para o seu produto.","6/7"),
 ("formbricks/formbricks","Formularios, NPS e pesquisa in-app.","6"),
 ("documenso/documenso","Assinatura digital de contratos (substitui Docusign em PMEs).","2/3"),
 ("papermark/papermark","Compartilhamento de documentos com analytics (proposta comercial).","2/4"),
 ("heyform/heyform","Construtor de formularios e quizzes.","9/10"),
 ("baptisteArno/typebot.io","Chatbot visual para captura de leads e qualificacao.","3/4"),
 ("calcom/cal.diy","Agendamento (substitui Calendly) - self-host e white-label.","2/3/5"),
 ("dubinc/dub","Encurtador de links com analytics e conversao.","6"),
 ("resend/react-email","E-mails transacionais em React (onboarding, cobranca, alertas).","6"),
]),
("Analytics, growth, observabilidade e qualidade", [
 ("PostHog/posthog","Product analytics + session replay + feature flags + experimentos.","6/8"),
 ("plausible/analytics","Analytics de site simples e privado (LGPD-friendly).","6"),
 ("umami-software/umami","Analytics self-hosted leve.","6"),
 ("growthbook/growthbook","Testes A/B e feature flags.","6/8"),
 ("highlight/highlight","Session replay e monitoramento de sessao.","6"),
 ("openreplay/openreplay","Gravacao de sessao self-hosted.","6"),
 ("metabase/metabase","BI simples: dashboards para o cliente sem escrever SQL.","3/11"),
 ("apache/superset","BI avancado para dados grandes.","11"),
 ("streamlit/streamlit","Apps de dados em Python em minutos (ferramenta interna paga).","3/11"),
 ("gradio-app/gradio","Demo e app web de modelo em 20 linhas (prova de conceito e Spaces).","3/4/5"),
 ("marimo-team/marimo","Notebook reativo em Python para analises compartilhaveis.","3/11"),
 ("grafana/grafana","Dashboards de infraestrutura e metricas de operacao.","6/8"),
 ("getsentry/sentry","Monitoramento de erros da sua aplicacao.","6"),
 ("SigNoz/signoz","APM e logs open source (alternativa ao Datadog).","6/8"),
 ("langfuse/langfuse","Observabilidade de LLM: rastreie prompts, custos e qualidade.","3/6/8"),
 ("promptfoo/promptfoo","Testes e avaliacao de prompts/modelos (qualidade antes de vender).","3/6/8"),
 ("louislam/uptime-kuma","Monitor de disponibilidade para voce e para clientes.","3/6"),
]),
("Agentes, orquestracao e RAG (codigo)", [
 ("langchain-ai/langchain","Ecossistema base para LLM: tools, RAG, chains, integracoes.","3/6"),
 ("langchain-ai/langgraph","Agentes com estado, ciclos e human-in-the-loop (producao).","3/6"),
 ("microsoft/autogen","Multiagentes conversacionais da Microsoft.","3/6"),
 ("microsoft/agent-framework","Framework oficial para orquestrar agentes em .NET/Python.","3/6"),
 ("crewAIInc/crewAI","Times de agentes com papeis: ideal para entregar servico automatizado.","3/4"),
 ("run-llama/llama_index","RAG e indexacao de documentos (o mais maduro para dados proprios).","3/6"),
 ("stanfordnlp/dspy","Programar prompts com otimizacao automatica (qualidade + custo).","6/7"),
 ("huggingface/smolagents","Agentes enxutos com foco em codigo.","3/6"),
 ("pydantic/pydantic-ai","Agentes tipados em Python, bom para producao.","6"),
 ("openai/openai-agents-python","SDK oficial de agentes da OpenAI (handoffs, guardrails).","3/6"),
 ("camel-ai/camel","Pesquisa e frameworks de agentes escalaveis.","7"),
 ("FoundationAgents/MetaGPT","Time de agentes que simula uma empresa de software.","9"),
 ("letta-ai/letta","Memoria de longo prazo para agentes (antes MemGPT).","6/8"),
 ("mem0ai/mem0","Camada de memoria para assistentes personalizados.","6/8"),
 ("getzep/graphiti","Memoria temporal em grafo (relacionamentos e historico).","6/8"),
 ("agent0ai/agent-zero","Agente autonomo com interface, facil de demonstrar a cliente.","3"),
 ("kortix-ai/suna","Agente generalista com UI (produto pronto para revender/white-label).","3/8"),
 ("OpenHands/OpenHands","Agente de codigo autonomo (resolve issues, abre PR).","6/7"),
 ("Significant-Gravitas/AutoGPT","Plataforma de agentes com builder visual.","3/9"),
 ("deepset-ai/haystack","Pipelines de NLP/RAG com foco em producao.","6"),
 ("chroma-core/chroma","Banco vetorial leve para prototipos e RAG.","6"),
 ("qdrant/qdrant","Banco vetorial de producao, rapido e com filtros.","6/7"),
 ("weaviate/weaviate","Banco vetorial com busca hibrida.","6/7"),
 ("e2b-dev/E2B","Sandbox de execucao de codigo para agentes (seguranca).","7"),
]),
("Plataformas no-code/low-code de IA e automacao", [
 ("n8n-io/n8n","Automacao visual com 400+ integracoes + nos de IA. O cavalo de batalha do modelo 3.","3/4"),
 ("activepieces/activepieces","Alternativa MIT ao Zapier, self-host ilimitado.","3"),
 ("windmill-labs/windmill","Scripts Python/TS como workflows (dev-friendly).","3/7"),
 ("kestra-io/kestra","Orquestracao declarativa (YAML) para pipelines e jobs.","3/7"),
 ("huginn/huginn","Agentes de vigilancia web (monitorar preco, site, edital).","11"),
 ("triggerdotdev/trigger.dev","Jobs em background e filas para o seu SaaS.","6"),
 ("temporalio/temporal","Workflows duraveis para processos longos e confiaveis.","6/8"),
 ("langgenius/dify","Plataforma de apps de LLM: RAG, agente, workflow, API.","3/6"),
 ("FlowiseAI/Flowise","Construtor visual de fluxos de LLM e agentes (ARQUIVADO em 2026 - substitutos: Dify ou RAGFlow).","3"),
 ("infiniflow/ragflow","RAG de documentos com interface e citacoes.","3/6"),
 ("open-webui/open-webui","Chat estilo ChatGPT para a empresa, com RAG e usuarios.","3/8"),
 ("LibreChat-AI/LibreChat","Chat multi-modelo com plugins, agentes e multiusuario.","3/8"),
 ("Mintplex-Labs/anything-llm","Chat com seus documentos, desktop e servidor.","3/6"),
 ("onyx-dot-app/onyx","Busca e assistente corporativo sobre fontes internas.","3/8"),
 ("khoj-ai/khoj","Assistente pessoal sobre seus arquivos (segundo cerebro).","9/10"),
 ("appsmithorg/appsmith","Painel interno low-code (entregar ferramenta ao cliente rapido).","3"),
 ("ToolJet/ToolJet","Alternativa ao Retool, self-host.","3/6"),
 ("Budibase/budibase","Apps internos e automacoes com banco proprio.","3"),
 ("baserow/baserow","Airtable open source (base do back-office do cliente).","3/11"),
 ("teableio/teable","Planilha-database colaborativa e rapida.","3/11"),
 ("nocodb/nocodb","Airtable open source: transforma planilha em app.","3/11"),
 ("enescingoz/awesome-n8n-templates","280+ templates de n8n prontos (copie e adapte por setor).","3/5"),
 ("Zie619/n8n-workflows","2.000+ workflows automaticos coletados do site do n8n.","3/5"),
]),
("Codigo: assistentes, agentes e MCP", [
 ("anomalyco/opencode","Agente de codigo no terminal (ex-sst/opencode), open source.","6/7"),
 ("openai/codex","Agente de codigo oficial da OpenAI (CLI).","6/7"),
 ("google-gemini/gemini-cli","Agente de codigo no terminal com Gemini.","6/7"),
 ("cline/cline","Agente dentro do VS Code que edita e executa.","6"),
 ("RooCodeInc/Roo-Code","Suite de agentes de codigo no editor (ARQUIVADO em 2026 - substitutos: Cline ou opencode).","6"),
 ("Aider-AI/aider","Programacao por pares no terminal com git.","6"),
 ("aaif-goose/goose","Agente local extensivel (ex-block/goose).","6"),
 ("continuedev/continue","Autocomplete e chat de codigo com seus modelos.","6"),
 ("SWE-agent/SWE-agent","Agente que resolve issues do GitHub (pesquisa + pratica).","6/7"),
 ("modelcontextprotocol/servers","Servidores MCP de referencia (conecte modelos a ferramentas).","5/6"),
 ("punkpeye/awesome-mcp-servers","Lista gigante de servidores MCP existentes.","5/6"),
 ("lharries/whatsapp-mcp","MCP de WhatsApp: atendimento e follow-up automatizado.","3/4"),
 ("anthropics/claude-cookbooks","Receitas oficiais da Anthropic (RAG, tools, agentes).","3/6"),
 ("openai/openai-cookbook","Receitas oficiais da OpenAI (do basico ao avancado).","3/6"),
 ("e2b-dev/awesome-ai-agents","Mapa de frameworks de agentes por caso de uso.","3/6/7"),
]),
("Navegacao, scraping e documentos", [
 ("browser-use/browser-use","Agente que opera navegador como humano (formularios, portais, ERP web).","3/11"),
 ("browserbase/stagehand","Automacao de navegador com IA, foco em producao.","3/11"),
 ("Skyvern-AI/skyvern","Automacao de processos web por visao+LLM (licenca AGPL: cuidado).","3/11"),
 ("firecrawl/firecrawl","Crawler que entrega markdown limpo para LLM (AGPL: use como servico).","3/11"),
 ("unclecode/crawl4ai","Crawler leve e gratuito para pipelines de IA.","11"),
 ("scrapy/scrapy","Crawler classico, robusto e escalavel.","11"),
 ("apify/crawlee","Framework de scraping com anti-bloqueio e proxy.","11"),
 ("daijro/camoufox","Navegador anti-deteccao para coleta dificil.","11"),
 ("steel-dev/steel-browser","Navegador headless como API para agentes.","7/11"),
 ("microsoft/markitdown","Converte PDF/Office/HTML em markdown para LLM.","3/6"),
 ("docling-project/docling","Parsing de documentos complexos (tabelas, layout).","3/6"),
 ("opendatalab/MinerU","PDF cientifico/complexo para markdown estruturado.","3/11"),
 ("datalab-to/marker","PDF -> markdown de altissima qualidade (notas, contratos).","3/11"),
 ("datalab-to/surya","OCR e analise de layout multilingue.","3/11"),
 ("PaddlePaddle/PaddleOCR","OCR industrial multilingue e de tabelas.","3/11"),
 ("Unstructured-IO/unstructured","ETL de documentos para RAG.","3/11"),
 ("Stirling-Tools/Stirling-PDF","Kit de ferramentas de PDF self-hosted (assinar, dividir, OCR).","3/6"),
 ("gotenberg/gotenberg","API de conversao PDF/Office/HTML (gera relatorios).","6/8"),
]),
("Midia: audio, imagem, video", [
 ("openai/whisper","Transcricao de audio e video (99 idiomas). Base de atas e legendas.","2/5"),
 ("SYSTRAN/faster-whisper","Whisper 4x mais rapido (CTranslate2) - ideal para volume.","2/5"),
 ("m-bain/whisperX","Transcricao + alinhamento + diarizacao (quem falou o que).","2/5"),
 ("k2-fsa/sherpa-onnx","ASR/TTS on-device (sua app sem custo de API).","6"),
 ("Vaibhavs10/insanely-fast-whisper","Transcricao com maxima velocidade em GPU.","2/5"),
 ("collabora/WhisperLive","Transcricao em tempo real (legendas ao vivo).","5"),
 ("myshell-ai/MeloTTS","TTS multilingue rapido (inclui PT).","5/6"),
 ("rhasspy/piper","TTS local leve (ARQUIVADO em 2026 - substitutos: Kokoro-82M ou MeloTTS).","6"),
 ("fishaudio/fish-speech","TTS com clonagem de voz.","5"),
 ("SWivid/F5-TTS","TTS de alta qualidade por poucos segundos de audio.","5"),
 ("myshell-ai/OpenVoice","Clonagem de voz e conversao de tom.","5"),
 ("facebookresearch/demucs","Separacao de faixas (ARQUIVADO em 2026 - alternativa: separacao via ComfyUI/audio.cpp).","5"),
 ("Comfy-Org/ComfyUI","Estudio node-based de geracao de imagem/video local. Coracao da fabrica de criativos.","5"),
 ("AUTOMATIC1111/stable-diffusion-webui","UI classica de Stable Diffusion (ecossistema de extensoes).","5"),
 ("invoke-ai/InvokeAI","Estudio de imagem com controle profissional.","5"),
 ("Sanster/IOPaint","Remocao de objetos e inpainting local (ARQUIVADO em 2026 - alternativa: inpainting no ComfyUI).","5"),
 ("danielgatis/rembg","Remove fundo de imagens em lote.","5"),
 ("TencentARC/GFPGAN","Restauracao de rostos em fotos antigas.","5"),
 ("Tongyi-MAI/Z-Image","Geracao de imagem rapida e aberta (repo oficial do modelo).","5/6"),
 ("Wan-Video/Wan2.2","Geracao de video aberta (texto/imagem para video).","5"),
 ("hpcaitech/Open-Sora","Video generation open source.","5"),
 ("zai-org/CogVideo","Video generation com boa qualidade.","5"),
 ("facefusion/facefusion","Troca de rosto e edicao facial (exige cuidado etico/legal).","5"),
 ("deepinsight/insightface","Reconhecimento e analise facial (controle de acesso, moderacao).","6/11"),
 ("tencent-ailab/V-Express","Animacao de retrato por audio (avatares falantes).","5"),
 ("harry0703/MoneyPrinterTurbo","Gera video curto completo a partir de um tema (roteiro+voz+legendas).","5"),
 ("remotion-dev/remotion","Video programatico em React (renderiza em escala).","5"),
 ("huggingface/diffusers","Biblioteca de difusao (SD, FLUX, video) para pipelines proprios.","5/7"),
 ("FFmpeg/FFmpeg","Conversao e edicao de midia em linha de comando (a base de tudo).","5"),
]),
("Treinar, ajustar e servir modelos", [
 ("huggingface/transformers","A biblioteca padrao para usar/treinar milhares de modelos.","6/7"),
 ("huggingface/trl","Fine-tuning com RLHF/DPO (especializar modelo em um nicho).","7"),
 ("huggingface/peft","Fine-tuning eficiente (LoRA/QLoRA) com pouca VRAM.","7"),
 ("unslothai/unsloth","Treino 2x mais rapido e 70% menos VRAM (fine-tune barato).","7"),
 ("hiyouga/LlamaFactory","Fine-tuning de 100+ modelos sem escrever codigo.","7"),
 ("axolotl-ai-cloud/axolotl","Treino e fine-tune com arquivos de configuracao.","7"),
 ("artidoro/qlora","QLoRA original (referencia tecnica de treino em 1 GPU).","7"),
 ("unslothai/notebooks","Notebooks prontos de fine-tune por modelo (copie e rode).","7"),
 ("ggml-org/llama.cpp","Roda modelos GGUF localmente em CPU/GPU do cliente (on-premise).","6/7"),
 ("ollama/ollama","Modelos locais em 1 comando: prototipos e demos offline.","3/6"),
 ("vllm-project/vllm","Servidor de inferencia de alta vazao (base do modelo 7).","7"),
 ("huggingface/text-generation-inference","Servidor TGI (repositorio ARQUIVADO; migre para vLLM/TGI da HF).","7"),
 ("BerriAI/litellm","Gateway unico para 100+ provedores: cache, fallback e cotas por cliente.","6/7"),
 ("mistralai/mistral-inference","Inferencia Mistral (repositorio ARQUIVADO; use vLLM/transformers).","7"),
]),
("Verticais: e-commerce, comunidades e conteudo", [
 ("medusajs/medusa","Commerce headless (lojas, assinaturas, marketplaces).","6/8"),
 ("saleor/saleor","Plataforma de e-commerce GraphQL de nivel enterprise.","8"),
 ("vendurehq/vendure","E-commerce TypeScript extensivel.","8"),
 ("woocommerce/woocommerce","E-commerce WordPress (99% das PMEs que voce vai atender).","3/6"),
 ("bagisto/bagisto","Loja completa Laravel.","8"),
 ("spree/spree","E-commerce Ruby maduro.","8"),
 ("TryGhost/Ghost","Blog + newsletter + membros pagos (infoproduto com assinatura).","9/10"),
 ("discourse/discourse","Forum/comunidade completa (modelo 10).","10"),
 ("NodeBB/NodeBB","Forum moderno e leve.","10"),
 ("apache/answer","Q&A estilo Stack Overflow para uma comunidade de nicho.","10"),
]),
("Dados, financas e verticais especializadas", [
 ("openbq-org/OpenBB","Plataforma de dados financeiros (base para terminal de nicho).","11"),
 ("freqtrade/freqtrade","Bot de trading com backtesting (automatizar estrategia propria).","11"),
 ("hummingbot/hummingbot","Market making e execucao em exchanges.","11"),
 ("jesse-ai/jesse","Framework de research e backtest de cripto.","11"),
 ("microsoft/qlib","Plataforma de investimento com IA (quant research).","11"),
 ("airbytehq/airbyte","Centenas de conectores de dados (ETL para o seu produto).","7/11"),
 ("dbt-labs/dbt","Transformacao de dados em SQL (analytics confiavel).","11"),
 ("BrasilAPI/BrasilAPI","APIs publicas brasileiras (CEP, CNPJ, bancos, feriados).","6/11"),
 ("guibranco/BancosBrasileiros","Lista oficial de bancos brasileiros (validacao de dados).","6/11"),
]),
("Front-end, ferramentas de dev e produtividade", [
 ("shadcn-ui/ui","Componentes copia-e-cola que definem o padrao visual de SaaS em 2026.","6"),
 ("tailwindlabs/tailwindcss","CSS utilitario: prototipe telas em horas.","6"),
 ("honojs/hono","Framework web ultraleve (APIs e edge functions).","6/7"),
 ("trpc/trpc","Type-safety de ponta a ponta entre front e back.","6"),
 ("TanStack/query","Cache e estado de dados no front (UX de app).","6"),
 ("drizzle-team/drizzle-orm","ORM TypeScript leve e tipado.","6"),
 ("prisma/orm","ORM com migracoes e DX excelente.","6"),
 ("vercel/ai","AI SDK: streaming, tools e UI de chat em Next.js.","6"),
 ("vercel/chatbot","Chatbot completo de referencia (Next.js + AI SDK).","6/8"),
 ("anomalyco/sst","Infra como codigo: deploy em AWS com pouca cerimonia.","6/7"),
 ("steven-tey/novel","Editor de texto com IA (base para editor vertical).","6"),
 ("excalidraw/excalidraw","Quadro branco virtual (vender como whiteboard com IA).","6/9"),
 ("tldraw/tldraw","Canvas infinito SDK (produtos visuais e colaborativos).","6"),
 ("microsoft/playwright","Testes e automacao de navegador confiaveis.","3/11"),
 ("puppeteer/puppeteer","Automacao de Chrome (scraping e rotinas).","11"),
]),
("Aprender, listas e descoberta", [
 ("sindresorhus/awesome","A lista das listas: comece por ela e siga o topico que precisa.","-"),
 ("awesome-selfhosted/awesome-selfhosted","Tudo que pode ser self-hosted (corte de custo e privacidade).","-"),
 ("Shubhamsaboo/awesome-llm-apps","Apps de LLM com codigo (copie, adapte, venda).","-"),
 ("f/prompts.chat","Maior colecao de prompts da internet (inclui PT-BR).","9/12"),
 ("dair-ai/Prompt-Engineering-Guide","Guia tecnico de prompts (nivel profesional).","-"),
 ("microsoft/generative-ai-for-beginners","Curso oficial de IA generativa em 21 licoes (gratis).","-"),
 ("microsoft/AI-For-Beginners","Curso de IA em 12 semanas (fundamentos).","-"),
 ("huggingface/agents-course","Curso de agentes da Hugging Face (com certificado).","-"),
 ("kyrolabs/awesome-langchain","Mapa do ecossistema LangChain.","-"),
 ("mezod/awesome-indie","Recursos de negocio indie: precificacao, marketing, distribuicao.","-"),
]),
]
